const AssetPack = {
  icons: {
    CARDS: require("./../assets/icons/icon_cards_normal.svg").default,
    CARDS_GREEN: require("./../assets/icons/icon_cards_green.svg").default,
    ICON_404: require("./../assets/icons/404.svg").default,
    ARROW_LEFT: require("./../assets/icons/icon_back.svg").default,
    LUCKY_SYMBOL: require("./../assets/icons/iconLuckyNumber.svg").default,
    TICKET: require("./../assets/image/icon_ticket.png"),
    DOUBLE_DASH: require("./../assets/icons/double_dash.svg").default,
    COPY: require("../assets/icons/iconCopy.svg").default,
    TICK: require("../assets/icons/icon-tick.svg").default,
    GOLDEN_TICKET: require("../assets/icons/gold-ticket.svg").default,
    GREEN_TICKET: require("../assets/icons/green-ticket.svg").default,
    STARS: require("../assets/icons/new.svg").default,
  },
  logos: {
    TURBO_SCRATCH: require("./../assets/image/turbo_scratch_logo.png"),
  },
  backgrounds: {
    DAILY_CARD_BACKGROUND: require("./../assets/image/day_card_background.png"),
    DAILY_CARD_EXTRA_BACKGROUND: require("./../assets/image/day_card_extra_background.webp"),
    CARD_NUMBER_SET: require("./../assets/image/card_set_number_background.svg").default,
    CARD_NUMBER_SET_COMPLETED: require("./../assets/image/card_set_number_completed.svg").default,
    CARD_NUMBER_SET_INACTIVE: require("./../assets/image/card_set_number_inactive.svg").default,
    BOTTOM_GRADIENT: require("./../assets/image/background_bottom_gradient.svg").default,
    NEXT_DRAW_CARD: require("./../assets/image/next_draw_card_background.png"),
    BLUE_BACKGROUND_CARD: require("./../assets/image/resultsCard.svg").default,
    CHEST: require("./../assets/image/thank-you-for-playing.webp"),
    CLOCK: require("./../assets/image/background_clock.jpg"),
    GOLD_SACK: require("./../assets/image/background_gold_sack.jpg"),
    CONGRATS_BACKGROUND: require("./../assets/image/winner-bg.webp"),
    SCRACHIE: require("./../assets/image/background_scrachie.jpg"),
    SCRACHIE_404: require("./../assets/image/404-bg.webp"),
    TOP_NAV_DAILY: require("./../assets/image/question_hero.webp"),
    TOP_NAV_DRAW_IN_PROGRESS: require("./../assets/image/fortune.webp"),
    TOP_NAV_EXTENDING_PLAY: require("./../assets/image/hero_extend.webp"),
    TOP_NAV_HEROES: require("./../assets/image/img_landing_hero.webp"),
    TOP_NAV_START: require("./../assets/image/start_hero.webp"),
    TOP_NAV_FINISH: require("./../assets/image/fin_hero.webp"),
    TOP_NAV_LEADER_BOARD: require("./../assets/image/hero_leadeerboard.webp"),
    TOP_NAV_LEARN: require("./../assets/image/hero_learn.webp"),
    TOP_NAV_THANK_YOU: require("./../assets/image/cowgril.webp"),
    TOP_NAV_GODS_ARE_IMPRESSED: require("./../assets/image/gods_are_impressed.webp"),
    INFO_PAGE: require("./../assets/image/secondary-bg.webp"),
    POINTS_TAB: require("./../assets/image/points-tab.svg"),
  },
  videos: {
    WIN_LUCKY_SYMBOL: require("./../assets/video/3D_Lucky_Coin_Spin_Win_intro_safari.mp4"),
    WIN_LUCKY_SYMBOL_CHROME: require("./../assets/video/3D_Lucky_Coin_Spin_Win_intro_chrome.webm"),
    LUCKY_SYMBOL_FINAL: require("./../assets/video/lucky_symbol_3d_coin_cut.mp4"),
    TOP_NAV_HEROES: require("./../assets/video/landing.mp4"),
    TOP_NAV_LEADER_BOARD: require("./../assets/video/leaderboard.mp4"),
    TOP_NAV_DAILY: require("./../assets/video/question.mp4"),
    TOP_NAV_LEARN: require("./../assets/video/learn.mp4"),
    TOP_NAV_EXTENDING_PLAY: require("./../assets/video/extend-play.mp4"),
    TOP_NAV_DRAW_IN_PROGRESS: require("./../assets/video/fortune.mp4"),
    TOP_NAV_THANK_YOU: require("./../assets/video/cowgril.mp4"),
    TOP_NAV_GODS_ARE_IMPRESSED: require("./../assets/video/gods_are_impressed.mp4"),
    TOP_NAV_START: require("./../assets/video/start_hero.mp4"),
    TIMER_CARD: require("./../assets/video/timer_card_video.mp4"),
  },
  sounds: {
    COMBO: require(`./../assets/sounds/combo.mp3`),
    NICE_COMBO: require(`./../assets/sounds/nice_combo.mp3`),
    ULTRA_COMBO: require(`./../assets/sounds/ultra_combo.mp3`),
  },
  images: {
    PHAROAH: require("./../assets/image/pharoah.png"),
    CAROUSEL_ITEM_1: require("../assets/image/carousel/carousel_item_1.png"),
    CAROUSEL_ITEM_2: require("../assets/image/carousel/carousel_item_2.png"),
    CAROUSEL_ITEM_3: require("../assets/image/carousel/carousel_item_3.png"),
    CAROUSEL_ITEM_4: require("../assets/image/carousel/carousel_item_3.png"),
    CAROUSEL_ITEM_5: require("../assets/image/carousel/carousel_item_3.png"),
    EXTENDING_PLAY: require("./../assets/image/extending_play_image.png"),
    AMAZON_GOLD_GIFT_CARD: require("./../assets/image/amazon-gift-card.webp"),
    TURBO_GAME_CARDS_SHOW: require("./../assets/image/turbo_game_cards_show.png"),
    SCRATCH_CARD_FOREGROUND: require("./../assets/image/scratch_foreground.jpg"),
    TIME_IS_ON_YOUR_SIDE: require("./../assets/image/tim-is-on-your-side.webp"),
    DRAW_IN_PROGRESS: require("./../assets/image/draw-in-progress.webp"),
    CHEST: require("./../assets/image/thank-you-for-playing.webp"),
    BLANK: require("./../assets/image/poster_blank.png"),
  },
  lotties: {
    CTA_BUTTON_FULL_WIDTH: require("./../assets/lotties/buttonCallToActionFullWidth.json"),
    CTA_BUTTON_HALF_WIDTH: require("./../assets/lotties/buttonCallToActionHalf.json"),
    CTA_BUTTON_TWO_THIRD: require("./../assets/lotties/buttonCallToActionTwoThird.json"),
    THUMBS_UP: require("./../assets/lotties/lottieThumbsUp.json"),
    CONFETTI: require("../assets/lotties/lottieConfetti.json"),
    COUNT_DOWN: require("../assets/lotties/lottieInitialCountdown.json"),
    COUNT_DOWN_BONUS: require("../assets/lotties/lottieCountdownBonus.json"),
    TICKET_ENTRY: require("../assets/lotties/lottieTicketEntry.json"),
    COMBO_2X: require("../assets/lotties/ComboHolderMaxVersion-2x.json"),
    COMBO_3X: require("../assets/lotties/ComboHolderMaxVersion-3x.json"),
    COMBO_4X: require("../assets/lotties/ComboHolderMaxVersion-4x.json"),
    WIN: require("../assets/lotties/lottieMagicLetterWINheader.json"),
    SPIN_WHEEL: require("../assets/lotties/specialEventsCasinoHomeCarousel.json"),
    CARD_COUNT_DOWN: require("../assets/lotties/lottieCardCountdown.json"),
    SCRATCHIE_BUBBLE_POP_ERROR: require("../assets/lotties/lottieScratchieBubblePopError.json"),
    SCROLL_DOWN_CHEVRON: require("../assets/lotties/scroll_down_chevron.json")
  }
};

export default AssetPack;
