const AssetPack = {
  icons: {
    CARDS: require("./../assets/icons/icon_cards_normal.svg").default,
    CARDS_GREEN: require("./../assets/icons/icon_cards_green.svg").default,
    ICON_404: require("./../assets/icons/404.svg").default,
    ARROW_LEFT: require("./../assets/icons/icon_back.svg").default,
    LUCKY_SYMBOL: require("./../assets/icons/iconLuckyNumber.svg").default,
    TICKET: require("./../assets/image/icon_ticket.png"),
    DOUBLE_DASH: require("./../assets/icons/double_dash.svg").default,
    COPY: require("../assets/icons/iconCopy.svg").default,
    TICK: require("../assets/icons/icon-tick.svg").default,
    GOLDEN_TICKET: require("../assets/icons/gold-ticket.svg").default,
    GREEN_TICKET: require("../assets/icons/green-ticket.svg").default,
  },
  logos: {
    TURBO_SCRATCH: require("./../assets/image/turbo_scratch_logo.png"),
  },
  backgrounds: {
    DAILY_CARD_BACKGROUND: require("./../assets/image/day_card_background.png"),
    DAILY_CARD_EXTRA_BACKGROUND: require("./../assets/image/day_card_extra_background.webp"),
    CARD_NUMBER_SET: require("./../assets/image/card_set_number_background.svg").default,
    CARD_NUMBER_SET_COMPLETED: require("./../assets/image/card_set_number_completed.svg").default,
    CARD_NUMBER_SET_INACTIVE: require("./../assets/image/card_set_number_inactive.svg").default,
    BOTTOM_GRADIENT: require("./../assets/image/background_bottom_gradient.svg").default,
    NEXT_DRAW_CARD: require("./../assets/image/next_draw_card_background.png"),
    BLUE_BACKGROUND_CARD: require("./../assets/image/resultsCard.svg").default,
    GAME_TOP_LAYOUT: require("./../assets/image/background_top_layout.png"),
    GAME_TOP_LAYOUT_RED: require("./../assets/image/background_top_layout_red.png"),
    GAME_TOP_LAYOUT_YELLOW: require("./../assets/image/background_top_layout_yellow.png"),
    GAME_TOP_LAYOUT_GREEN: require("./../assets/image/background_top_layout_green.png"),
    CHEST: require("./../assets/image/background_chest.jpg"),
    CLOCK: require("./../assets/image/background_clock.jpg"),
    GOLD_SACK: require("./../assets/image/background_gold_sack.jpg"),
    CONGRATS_BACKGROUND: require("./../assets/image/congratulations_background.jpg"),
    SCRACHIE: require("./../assets/image/background_scrachie.jpg"),
    TOP_NAV_DAILY: require("./../assets/image/hero_question.webp"),
    TOP_NAV_DRAW_IN_PROGRESS: require("./../assets/image/scratch_draw_in_progress.jpg"),
    TOP_NAV_EXTENDING_PLAY: require("./../assets/image/hero_extend.webp"),
    TOP_NAV_HEROES: require("./../assets/image/scratch_heroes.webp"),
    TOP_NAV_LEADER_BOARD: require("./../assets/image/hero_leadeerboard.webp"),
    TOP_NAV_LEARN: require("./../assets/image/hero_learn.webp"),
    TOP_NAV_THANK_YOU: require("./../assets/image/scratch_thank_you.jpg"),
    TOP_NAV_GODS_ARE_IMPRESSED: require("./../assets/image/scratch_gods_are_impressed.jpg"),
    INFO_PAGE: require("./../assets/image/secondary-bg.webp")
  },
  videos: {
    WIN_LUCKY_SYMBOL: require("./../assets/video/3D_Lucky_Coin_Spin_Win_intro_safari.mp4"),
    WIN_LUCKY_SYMBOL_CHROME: require("./../assets/video/3D_Lucky_Coin_Spin_Win_intro_chrome.webm"),
    LUCKY_SYMBOL_FINAL: require("./../assets/video/lucky_symbol_3d_coin_cut.mp4"),
    DRAW_IN_PROGRESS_BACKGROUND: require("./../assets/video/draw_in_progress_background.mp4"),
  },
  sounds: {
    COMBO: require(`./../assets/sounds/combo.mp3`),
    NICE_COMBO: require(`./../assets/sounds/nice_combo.mp3`),
    ULTRA_COMBO: require(`./../assets/sounds/ultra_combo.mp3`),
  },
  images: {
    PHAROAH: require("./../assets/image/pharoah.png"),
    CAROUSEL_ITEM_1: require("../assets/image/carousel/carousel_item_1.png"),
    CAROUSEL_ITEM_2: require("../assets/image/carousel/carousel_item_2.png"),
    CAROUSEL_ITEM_3: require("../assets/image/carousel/carousel_item_3.png"),
    CAROUSEL_ITEM_4: require("../assets/image/carousel/carousel_item_3.png"),
    CAROUSEL_ITEM_5: require("../assets/image/carousel/carousel_item_3.png"),
    EXTENDING_PLAY: require("./../assets/image/extending_play_image.png"),
    AMAZON_GOLD_GIFT_CARD: require("./../assets/image/amazon_gift_card_golden.png"),
    TURBO_GAME_CARDS_SHOW: require("./../assets/image/turbo_game_cards_show.png"),
    SCRATCH_CARD_FOREGROUND: require("./../assets/image/scratch_foreground.jpg"),
    TIME_IS_ON_YOUR_SIDE: require("./../assets/image/tim-is-on-your-side.webp"),
  },
  lotties: {
    CTA_BUTTON_FULL_WIDTH: require("./../assets/lotties/buttonCallToActionFullWidth.json"),
    CTA_BUTTON_HALF_WIDTH: require("./../assets/lotties/buttonCallToActionHalf.json"),
    CTA_BUTTON_TWO_THIRD: require("./../assets/lotties/buttonCallToActionTwoThird.json"),
    THUMBS_UP: require("./../assets/lotties/lottieThumbsUp.json"),
    CONFETTI: require("../assets/lotties/lottieConfetti.json"),
    COUNT_DOWN: require("../assets/lotties/lottieInitialCountdown.json"),
    COUNT_DOWN_BONUS: require("../assets/lotties/lottieCountdownBonus.json"),
    TICKET_ENTRY: require("../assets/lotties/lottieTicketEntry.json"),
    COMBO_2X: require("../assets/lotties/ComboHolderMaxVersion-2x.json"),
    COMBO_3X: require("../assets/lotties/ComboHolderMaxVersion-3x.json"),
    COMBO_4X: require("../assets/lotties/ComboHolderMaxVersion-4x.json"),
    WIN: require("../assets/lotties/lottieMagicLetterWINheader.json"),
    SPIN_WHEEL: require("../assets/lotties/specialEventsCasinoHomeCarousel.json"),
    CARD_COUNT_DOWN: require("../assets/lotties/lottieCardCountdown.json"),
    SCRATCHIE_BUBBLE_POP_ERROR : require("../assets/lotties/lottieScratchieBubblePopError.json"),
  }
};

export default AssetPack;
